import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, Minus, HelpCircle } from 'lucide-react';

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const faqs = [
    {
      q: "How accurate is the content generated by the AI?",
      a: "Our models are fine-tuned on top-tier copywriting principles and SEO best practices. While the AI produces highly coherent and grammatically correct copies, we always recommend a brief editorial review to ensure facts and specific brand nuances align perfectly with your guidelines."
    },
    {
      q: "Can I customize the tone and style of the writing?",
      a: "Yes! Every template allows you to specify a target audience and tone of voice—ranging from professional and academic to witty, engaging, and casual. You can also feed specific rules or brand voices in the prompt instructions."
    },
    {
      q: "What languages do the tools support?",
      a: "We support generation in over 25+ languages, including English, Spanish, French, German, Italian, Portuguese, Japanese, Chinese, and many more. The AI automatically matches your language choice."
    },
    {
      q: "How does the billing and word count calculation work?",
      a: "For Starter plans, word counts are calculated based on the raw words generated by the AI models during editor runs. In Professional and Enterprise plans, word counts are completely unlimited so you never have to worry about hitting limits."
    },
    {
      q: "Is there a free trial or refund policy?",
      a: "Yes, we offer a 7-day free trial on our Professional plan. If you choose to upgrade and decide RankPilot isn't the right fit, you can cancel within the first 14 days for a full refund—no questions asked."
    }
  ];

  const toggleFAQ = (index) => {
    if (openIndex === index) {
      setOpenIndex(null);
    } else {
      setOpenIndex(index);
    }
  };

  return (
    <section id="faq" className="py-24 bg-white border-t border-gray-100">
      <div className="max-w-[800px] mx-auto px-6">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <span className="text-sm font-extrabold uppercase text-teal-brand tracking-wider mb-3 block">
            Questions
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-gray-900 mb-4 tracking-tight">
            Frequently asked questions
          </h2>
          <p className="text-gray-600">
            Everything you need to know about the RankPilot AI platform and billing systems.
          </p>
        </div>

        {/* FAQs Accordion */}
        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div 
                key={idx}
                className={`border rounded-2xl transition-all duration-300 ${
                  isOpen 
                    ? 'border-teal-brand/30 bg-teal-50/10 shadow-sm' 
                    : 'border-gray-100 hover:border-gray-200 bg-white'
                }`}
              >
                <button
                  onClick={() => toggleFAQ(idx)}
                  className="w-full flex items-center justify-between p-6 text-left cursor-pointer"
                >
                  <span className="font-bold text-gray-950 text-base sm:text-lg pr-4">
                    {faq.q}
                  </span>
                  <div className={`p-1.5 rounded-lg shrink-0 transition-colors ${
                    isOpen ? 'bg-teal-brand text-white' : 'bg-gray-50 text-gray-400'
                  }`}>
                    {isOpen ? <Minus size={18} /> : <Plus size={18} />}
                  </div>
                </button>

                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3 }}
                      className="overflow-hidden"
                    >
                      <div className="px-6 pb-6 pt-0 text-sm sm:text-base text-gray-500 leading-relaxed border-t border-gray-100/50">
                        {faq.a}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
};

export default FAQ;
